spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2055067@donga.ac.kr
    password: wxhpbfrorvotrjro
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/recycle
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
