spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2055067@donga.ac.kr
    password: wxhpbfrorvotrjro
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/recycle
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

jwt:
  access_expiration_time: 86400000
  refresh_expiration_time: 604800000
  secret: 5PL44yz7ghu3kN0BRguW0B8N1wtDjeCqI6phlMl63cI=
